// Player blob — three layered 16×16 sprites so eyes can blink without
// redrawing the body. See docs/design-handoff/README.md § "Player blob".

export const SPR_BLOB_BODY = `
....oooooo......
..oollllllooo...
.ollblllllbloo..
.oblllllllllbo..
oblllllllllllo..
obllllllllblblo.
obllllblblbbblo.
obllllllllblllo.
.obllllllllllo..
.obblllbbblllbo.
.ooblllllllbboo.
..ooobllblboooo.
....oooblboo....
......obbbo.....
.....ooboo......
......ooo.......
`;

export const SPR_BLOB_EYES_OPEN = `
................
................
................
................
................
....oo..oo......
....oo..oo......
................
................
................
................
................
................
................
................
................
`;

export const SPR_BLOB_MOUTH = `
................
................
................
................
................
................
................
.....oooo.......
................
................
................
................
................
................
................
................
`;

// Hazmat blob — same silhouette as SPR_BLOB_BODY but the body fill is the
// warm accent yellow ('y') instead of light periwinkle ('l'). Worn outside
// the bunker, where the air is hostile.
export const SPR_BLOB_BODY_HAZMAT = `
....oooooo......
..ooyyyyyyooo...
.oyybyyyyybyoo..
.obyyyyyyyyybo..
obyyyyyyyyyyyo..
obyyyyyyyybybyo.
obyyyybybybbbyo.
obyyyyyyyybyyyo.
.obyyyyyyyyyyo..
.obbyyybbbyyybo.
.ooyyyyyyyybboo.
..oooyybybooooo.
....oooyboo.....
......obbbo.....
.....ooboo......
......ooo.......
`;

// Helmet bubble — light-blue outline that sits over the upper half of the
// hazmat blob. Drawn as a separate sprite layer so it can have its own glassy
// alpha and stay independent of the body's breathe scale.
export const SPR_BLOB_HELMET = `
....llllll......
..ll......ll....
.l..........l...
.l..........l...
l............l..
l............l..
l............l..
l............l..
.l..........l...
.l..........l...
..llllllllll....
................
................
................
................
................
`;

// 11×10 blob bust used in the dialogue-box portrait frame.
export const SPR_BLOB_PORTRAIT = `
...bbbb....
..bllllbo..
.blllllbo..
.bllblllbo.
bllllblllbo
blooolloolo
bllllllllbo
.bllllllbo.
..ooobbbo..
....oboo...
`;

export const SPR_CAN_HELD = `
.....rrrrrr.
....rrrrrrro
...rrrrrrrro
...rrrrrrrrr
.....oooooor
............
............
............
`;
