// Player blob — three layered 16×16 sprites so eyes can blink without
// redrawing the body. See docs/design-handoff/README.md § "Player blob".

export const SPR_BLOB_BODY = `
....oooooo......
..oollllllooo...
.ollblllllbloo..
.oblllllllllbo..
oblllllllllllo..
obllllllllblblo.
obllllblblbbblo.
obllllllllblllo.
.obllllllllllo..
.obblllbbblllbo.
.ooblllllllbboo.
..ooobllblboooo.
....oooblboo....
......obbbo.....
.....ooboo......
......ooo.......
`;

export const SPR_BLOB_EYES_OPEN = `
................
................
................
................
................
....oo..oo......
....oo..oo......
................
................
................
................
................
................
................
................
................
`;

export const SPR_BLOB_MOUTH = `
................
................
................
................
................
................
................
.....oooo.......
................
................
................
................
................
................
................
................
`;

// 11×10 blob bust used in the dialogue-box portrait frame.
export const SPR_BLOB_PORTRAIT = `
...bbbb....
..bllllbo..
.blllllbo..
.bllblllbo.
bllllblllbo
blooolloolo
bllllllllbo
.bllllllbo.
..ooobbbo..
....oboo...
`;

export const SPR_CAN_HELD = `
.....rrrrrr.
....rrrrrrro
...rrrrrrrro
...rrrrrrrrr
.....oooooor
............
............
............
`;
