// 10 canonical plant species. ASCII is copied verbatim from
// docs/design-handoff/src/art-pocket.jsx (the PLANT_* constants).
// Treat these strings as canonical — do not "clean them up".

export const PLANT_BELL = `
.....bbbo.....
....bllllo....
...bllrrllo...
..olllrrrloo..
..ollrrrlloo..
..olllrrlloo..
...obllllo....
....opoo......
.....po.......
.....po.......
....opoo......
...opo.go.....
..opoooGoo....
..gGoGgGggo...
`;

export const PLANT_STAR = `
.....oyo......
....oyyyo.....
..ooyyyyyoo...
.oyyyyyyyyo...
oyyyyrroyyyoo.
.oyyyrroyyyo..
..oyyyrryoo...
....ooyooo....
.....opo......
....opoo......
....opo.go....
...opo.gGo....
..opooogggo...
.oGooggGoooo..
`;

export const PLANT_CRYS = `
.......o......
......obo.....
.....obblo....
...o.obblo....
..olo.bblo.bo.
..olbo.bloblo.
..oblbo.olbblo
.obbllo.olbblo
.oblllbo.lblo.
.olllllbobblo.
.ooblllbbobo..
..oobllobboo..
...ooooooo....
....oooo......
`;

export const PLANT_DREAM = `
....oooooo....
...oblllllo...
..obllllllbo..
..olloooollo..
.obloollooblo.
.obloocooblo..
.obloocoolblo.
..obllooolbo..
..obllllllbo..
...obllllbo...
.....opo......
.....opo......
....opoo......
...gGoGggo....
`;

export const PLANT_ROSE = `
.....oro......
....orrro.....
...orrrro.....
....oro..oro..
....opo.orro..
....opoorrro..
....opoo.oro..
.oro.po.......
orrropo.......
.oro.po.......
.....po.go....
....opoogGo...
...opooogggo..
..oGooggGooo..
`;

export const PLANT_FERN = `
.....bbo......
....bllbo.....
...bllllo.....
...obllloo....
....obbbo.....
.....opo......
....opo.......
...opo.ggo....
..opo..gGgo...
.opo..gGggo...
opo..gGggGo...
po..gGggGo....
po..gGggo.....
oGggGgoo......
`;

export const PLANT_POD = `
......bbo.....
.....blllo....
....bllbllo...
....blllllo...
..oolbllblo...
..oollllooo...
....opo.bbo...
....opoblllo..
....opolllo...
....opo.oo....
....opo.......
....opo.go....
...opoogGo....
..opooogggo...
`;

export const PLANT_THORN = `
.....o........
.....bo.......
....blo.......
....bloo......
o..oblo.......
bo.oblo.ooo...
blo.oblo.oboo.
oblo.olo.olbo.
.obloolboolo..
.oblllllbblo..
..ooblllboo...
...oollloo....
....ooooo.....
.....go.......
`;

export const PLANT_CAP = `
.....oooo.....
...oorrrroo...
..orrrrrrrro..
.orrrrrrrrrro.
orrlllrrlllrrr
orrlllrrlllrrr
.oorrrrrrrroo.
...ocoooooc...
....occcc.....
....ocooc.....
....ocooc.....
....ocooc.....
....occcc.....
....oooo......
`;

export const PLANT_ORB = `
......yo......
.....yo.......
.....yoyo.....
....yo..o.....
....yo.yyo....
.....yoyo.....
....yo.r......
...yo..rr.....
..yo..rro.....
..yo.rrro.....
...yo.go......
....yogGo.....
...yogggo.....
..oGoogGoo....
`;

export const ALL_PLANTS = {
  bell: PLANT_BELL,
  star: PLANT_STAR,
  crys: PLANT_CRYS,
  dream: PLANT_DREAM,
  rose: PLANT_ROSE,
  fern: PLANT_FERN,
  pod: PLANT_POD,
  thorn: PLANT_THORN,
  cap: PLANT_CAP,
  orb: PLANT_ORB,
} as const;

export type PlantId = keyof typeof ALL_PLANTS;
